### ISSUE TITLE
How do get CPU IO Wait percentage?

### ISSUE THREAD

**Issue by xanview** [djberg96/sys-cpu#6]
I'm seeing this for cpu_stats, but I don't believe it has the IO wait, can this be added? - also the documentation doesn't explain what each field means.

``` ruby
time-agent(staging)> pp Sys::CPU.cpu_stats
{"cpu0"=>[7844, 173729, 35516, 643869, 9160, 0, 16284, 0, 0, 0],
 "cpu1"=>[7675, 195246, 37371, 654452, 8526, 0, 823, 0, 0, 0],
 "cpu2"=>[7887, 198639, 38249, 649043, 9305, 0, 828, 0, 0, 0],
 "cpu3"=>[7899, 202505, 38929, 644832, 8797, 0, 836, 0, 0, 0]}
```

**Comment by djberg96** [comment]
@ghost, The code collects all the values that /proc/stats provides, so it should be there.  The first seven values are:

```
    user: normal processes executing in user mode
    nice: niced processes executing in user mode
    system: processes executing in kernel mode
    idle: twiddling thumbs
    iowait: waiting for I/O to complete
    irq: servicing interrupts
    softirq: servicing softirqs
```

I'm not sure what the last three numbers are, I can't find them explained anywhere. You're right that the docs could use an update.

**Comment by djberg96** [comment]
Update, I found fields 8 and 9 are for virtual environments:
```
steal: time stolen by other operating systems running in a virtual environment (since 2.6.11)
guest: time spent for running a virtual CPU or guest OS under the control of the kernel (since 2.6.24)
```
Not sure what the 9th one is, but I'm guessing it's something similar.

**Comment by djberg96** [comment]
@ghost, I've updated the docs, and will include that information in the next release. Thanks!
